### ISSUE TITLE
消息组件删除后被调用

### ISSUE THREAD

**Issue by wxj881027** [XCWQW1/DDNetToolBox#72]
当你打开文件资源管理器选择添加的cfg时,成功添加一次之后,重复此操作,,不选择直接退出会报错崩溃,日志如下:
Traceback (most recent call last):
  File "C:\Users\26315\AppData\Local\Temp\ONEFIL~1\qfluentwidgets\components\widgets\info_bar.py", line 190, in __fadeOut
RuntimeError: wrapped C/C++ object of type QPropertyAnimation has been deleted

**Comment by XCWQW1** [comment]
这玩意好像是概率性事件， https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/836 这里也有类似的，看起来挺难搞

**Comment by ZerolAcqua** [comment]
只要主动关闭弹出的消息条就都会有这个报错？
```
Traceback (most recent call last):
  File "C:\Users\LENOVO~1\AppData\Local\Temp\ONEFIL~2\qfluentwidgets\components\widgets\info_bar.py", line 190, in __fadeOut
RuntimeError: wrapped C/C++ object of type QPropertyAnimation has been deleted
```

**Comment by ZerolAcqua** [comment]
只要主动关闭弹出的消息条就都会有这个报错？
```
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Temp\ONEFIL~2\qfluentwidgets\components\widgets\info_bar.py", line 190, in __fadeOut
RuntimeError: wrapped C/C++ object of type QPropertyAnimation has been deleted
```

**Comment by XCWQW1** [comment]
比较玄学，我猜测是组件已经超时回收后用户二次删除 qt找不着就红的
