### ISSUE TITLE
渲染皮肤崩溃

### ISSUE THREAD

**Issue by XCWQW1** [XCWQW1/DDNetToolBox#74]
渲染 TEE 皮肤时 
如果皮肤目录中有 没有`alpha`层 的图片文件
会导致 Pillow 抛出 `ValueError: bad transparency mask` 的异常

报错内容已去隐处理
```
Traceback (most recent call last):
  File "C:\Users\...\app\view\resource_interface.py", line 220, in load_next_batch
  File "C:\Users\...\app\view\resource_interface.py", line 89, in __init__
  File "C:\Users\...\app\utils\draw_tee.py", line 104, in draw_tee
  File "C:\Users\...\app\utils\draw_tee.py", line 83, in crop_and_generate_image
  File "C:\Users\...\app\utils\draw_tee.py", line 71, in create_tee_image
  File "C:\Users\...\PIL\Image.py", line 1847, in paste
ValueError: bad transparency mask
```

由 - 在qq群内报告

**Comment by XCWQW1** [comment]
v1.1.6 已修复该问题
